name: cfp
on:
  push:
    branches: master
    paths: ['cfp/2022/**', '.github/workflows/2022-cfp.yml']
jobs:
  cfp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: yegor256/latexmk-action@0.11.1
        with:
          path: cfp/2022
          opts: -pdf
          packages: wrapfig xcolor hyperref changepage graphics fancyhdr textpos
      - run: mkdir output
      - run: mv cfp/2022/cfp.pdf output/iccq-cfp-2022.pdf
      - uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: pdf
          folder: output
          clean: false
