name: cfp
on:
  push:
    branches: master
    paths: ['cfp/2022/**', '.github/workflows/2022-cfp.yml']
jobs:
  cfp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.8.0
        with:
          path: cfp/2022
          opts: -pdf
          packages: wrapfig xcolor hyperref changepage graphics fancyhdr textpos
      - run: mkdir output
      - run: mv cfp/2022/cfp.pdf output/iccq-cfp-2022.pdf
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pdf
          folder: output
          clean: false
